### ISSUE TITLE
Insufficient privileges to operate on account 'KEBOOLA'

### ISSUE THREAD

**Issue by odinuv** [keboola/app-snowflake-dwh-manager#21]
Moc mi to teda neni jasny, jak se to muze stat

ErrorException:odbc_prepare(): SQL error: SQL access control error: Insufficient privileges to operate on account 'KEBOOLA', SQL state 42501 in SQLPrepare {\"errFile\":\"\/code\/vendor\/keboola\/php-csv-db-import\/src\/Snowflake\/Connection.php\",\"errLine\":167,\"errCode\":0,\"errTrace\":\"#0 [internal function]: Keboola\\\\Component\\\\BaseComponent::Keboola\\\\Component\\\\{closure}(2, 'odbc_prepare():...', '\/code\/vendor\/ke...', 167, Array)\\n#1 \/code\/vendor\/keboola\/php-csv-db-import\/src\/Snowflake\/Connection.php(167): odbc_prepare(Resource id #73, 'CREATE ROLE IF ...')\\n#2 \/code\/src\/Connection.php(236): Keboola\\\\Db\\\\Import\\\\Snowflake\\\\Connection->query('CREATE ROLE IF ...', Array)\\n#3 \/code\/src\/Connection.php(68): Keboola\\\\SnowflakeDwhManager\\\\Connection->query('CREATE ROLE IF ...')\\n#4 \/code\/src\/DwhManager.php(167): Keboola\\\\SnowflakeDwhManager\\\\Connection->createRole('PBP_OPERATIONAL...')\\n#5 \/code\/src\/DwhManager.php(117): Keboola\\\\SnowflakeDwhManager\\\\DwhManager->ensureRoleExists('PBP_OPERATIONAL...')\\n#6 \/code\/src\/Component.php(37): Keboola\\\\SnowflakeDwhManager\\\\DwhManager->checkUser(Object(Keboola\\\\SnowflakeDwhManager\\\\Configuration\\\\User))\\n#7 \/code\/src\/run.php(14): Keboola\\\\SnowflakeDwhManager\\\\Component->run()\\n#8 {main}\",\"errPrevious\":\"\"}

https://keboola.slack.com/archives/C09U3R1J4/p1541628730003700

**Comment by kacurez** [comment]
sa stalo nieco podobne `Insufficient privileges to operate on database 'DWHM_PRODUCTBOARD', SQL state 42501 in SQLPrepare\" while executing query \"CREATE SCHEMA IF NOT EXISTS \"MATUS_PRODUCTBOARD_COM\"`

https://keboola.slack.com/archives/C09U3R1J4/p1573558459007800
